### PR TITLE
Access to Private Bower Server Installations. SVN Credentials

### PR DESCRIPTION
**Pull request by itstueben**
Support Private-Bower-Server Installations like https://github.com/Hacklone/private-bower 

SVN Credentials: Use HTTP Basic Auth from Composer for your Repository URLs. Think in my next update it will be possible to overwrite by composer.json config Option.

### CODE REVIEW

**Comment by itstueben** [comment]
Can you merge my Pull Request to your trunk?

**Comment by francoispluchino** [comment]
I will see this PR tomorrow.

**Comment by francoispluchino** [comment]
Can you create a new PR for the doc, thanks.

**Comment by francoispluchino** [comment]
Thanks to rebase your PR for keep only one commit.

**Comment by itstueben** [comment]
Did you know when the new Version 1.2.0 will be released?

**Comment by francoispluchino** [comment]
I'll see and merge your PR this week-end. After, the release of the 1.2.0 version is not planned for this week, because there are an another PR in queue (but you will can use the dev-master version).

**Comment by francoispluchino** [comment]
I made some changes to the code style and configuration, I has added tests, and I has created a repository registry factory allowing us the to add multiple private registries (see affd665d3a2df21c790b89bf7e9d33b1e0ea39d9).

I have also move the formatting of the url with `svn+http` in the driver (34b3032cf32e070fe1f20897305a44d9fbc7e305).

Can you do me a return, if everything is ok for you?

**Comment by itstueben** [comment]
The changes to the "RegistryFactoryInterface" is the right way. Good Job! Thanks a lot!!!
And of course the "svn+http" check only make sense in the SVN Driver.

**Pull request merged**
