### PR TITLE
support wrong versioning in project

### PR DESCRIPTION
**Pull request by surikat**
eg: composer require bower-asset/jquery.layout

### CODE REVIEW

**Comment by francoispluchino** [comment]
If there is a bug with the version converter, it must be fixed, not skipped.

**Comment by surikat** [comment]
I agree in theory but if you are not the owner of the repository it can be problematic, et par ailleurs, bower have no problem with that, I think you want to offer a substituion of bower usage and if
```
bower install jquery.layout
```
works
```
composer require bower-asset/jquery.layout
```
should work too, or I'm wrong ?

**Comment by francoispluchino** [comment]
Yes, of course, but your fix is not correct. Add your problematic convestion of verion in [SemverConverterTest](https://github.com/francoispluchino/composer-asset-plugin/blob/master/Tests/Converter/SemverConverterTest.php), and fix it.

**Comment by surikat** [comment]
Ah ok, j'étais justement en train de me dire que j'avais mal compris, my bad, I will take a look

**Comment by surikat** [comment]
I fixed it

**Comment by francoispluchino** [comment]
Thanks to rebase your PR in 1 commit.

**Comment by francoispluchino** [comment]
And clean your style of code, use `php-cs-fixer`.

**Pull request closed without merging**
