### PR TITLE
Fix Deprecation Warning for VersionParser::parseLinks()

### PR DESCRIPTION
**Pull request by huebs**
Replace call to Composer\Package\Version\VersionParser::parseLinks()
with call to Composer\Package\Loader\ArrayLoader::parseLinks() as
suggested by the deprecation warning.

Update composer lock file so that the version of composer specified
includes the depreciation warning and newly added replacement method.

### CODE REVIEW

**Comment by stof** [comment]
yo should probably keep compatibility with older versions of Composer too for now, for people sticking to alpha releases of composer rather than nightly builds

**Comment by francoispluchino** [comment]
@stof Yes, that's what I was writing! You have unsheathed faster.

**Comment by samdark** [comment]
Is there a possibility to get Composer version runtime?

**Comment by francoispluchino** [comment]
Yes, see [Composer\Composer::VERSION](https://github.com/composer/composer/blob/69210d5bc130f8cc9f96f99582a041254d7b9833/src/Composer/Composer.php#L31)

**Comment by samdark** [comment]
Then for the sake of backwards compatibility one can use different methods based on the version number.

**Comment by stof** [comment]
Or just perform a ``method_exists`` check. The composer version is only bumped when a release is done, and the change has been done a long time after the previous release (and the next alpha release is not yet out), so a version check won't work to detect it

**Comment by huebs** [comment]
I've added `method_exists()` checks to the code and associated test. A few thoughts:

* Should this be encapsulate in a parseLinks() method so it can be tested independently?
* Should the ArrayLoader object be lazily instantiated as it's not needed if doesn't have the parseLinks() method?
* Should TravisCI be reconfigured to run the tests using both a legacy and the latest versions of Composer? Is that even possible?

**Comment by prawee** [comment]
i'm using "composer self-update --rollback"  to version 2015-07-07_14-15-59-dbdd497   that return working.

**Comment by samdark** [comment]
@francoispluchino seems that with function check this pull request is now backwards compatible,

**Comment by francoispluchino** [comment]
@huebs There is an error with your `composer require` command in [travis](https://travis-ci.org/francoispluchino/composer-asset-plugin/jobs/71422332#L154).

**Comment by re8us** [comment]
How to fix this warnings?

**Comment by samdark** [comment]
@re8us wait till it's merged.

**Comment by francoispluchino** [comment]
@huebs There is always an error. Can you fix it for that I merge your PR?

**Comment by samdark** [comment]
@francoispluchino is that error somehow related? I don't think so.

**Comment by francoispluchino** [comment]
@samdark Ok, I will test locally tonight.

**Comment by oliverhuckfeldt** [comment]
I fixed it by removing the .composer folder in my homedirectory.

**Comment by ezequieltejada** [comment]
@oliverhuckfeldt , didn't work for me

**Comment by SomniSom** [comment]
php composer.phar global update

**Comment by Black-Room-Boy** [comment]
I still have this problem. How to fix it ? I can not install yii2 because of this. Thanks

**Comment by francoispluchino** [comment]
Use the `v1.0.3` version of this plugin.

**Comment by agungsijawir** [comment]
@francoispluchino How can I know I am on `v1.0.3`?

I did this `php composer.phar global require "fxp/composer-asset-plugin:~1.0.3"` and this is the result:
```
Changed current directory to /home/vagrant/.composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
```

**Comment by francoispluchino** [comment]
```
$ composer global show fxp/composer-asset-plugin
```

Do you use the last version of Composer?

**Comment by agungsijawir** [comment]
I think I am on `v1.0.3`, no? Here is my result:
```
$ composer global show fxp/composer-asset-plugin
Changed current directory to /home/vagrant/.composer
name     : fxp/composer-asset-plugin
descrip. : NPM/Bower Dependency Manager for Composer
keywords : asset, bower, composer, dependency manager, nodejs, npm, package
versions : dev-master, 1.1.x-dev, * v1.0.3, v1.0.2, v1.0.1, v1.0.0, v1.0.0-beta4, v1.0.0-beta3, v1.0.0-beta2, v1.0.0-beta1
type     : composer-plugin
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/francoispluchino/composer-asset-plugin.git c2b0406ac19e9ea2d9556987e827d4e7f6924fde
dist     : [zip] https://api.github.com/repos/francoispluchino/composer-asset-plugin/zipball/c2b0406ac19e9ea2d9556987e827d4e7f6924fde c2b0406ac19e9ea2d9556987e827d4e7f6924fde
names    : fxp/composer-asset-plugin

autoload
psr-4
Fxp\Composer\AssetPlugin\ => .

requires
composer-plugin-api ^1.0
php >=5.3.3

requires (dev)
composer/composer ~1.0@dev
```

And here is my Composer version:
```
$ php composer.phar -V  
Composer version 1.0-dev (8f44f9cc67f2ccf9fd2a6fbe29b130e258295ca0) 2015-09-20 15:41:02
```

**Comment by francoispluchino** [comment]
And you have the deprecated warning?

**Comment by curlybeast** [comment]
I have this exact same situation. Same version too as agungsijawir.
Trying to install an extension for Yii (I've had to use the tarball to install Yii2 up to now because of this).
Any help would be greatly appreciated!

**Comment by francoispluchino** [comment]
This PR was to remove the warnings, and they don't block the install. So I don't understand... Can you be more clear?

**Comment by agungsijawir** [comment]
@francoispluchino No warning at all. Just red ErrorException:

```
[ErrorException]  
 Argument 1 passed to Fxp\Composer\AssetPlugin\Repository\BowerRepository::createVcsRepositoryConfig() must be of the type array, null given, called in /home/vagrant/.composer/vendor/fxp/composer-asset-plugin  
  /Repository/AbstractAssetsRepository.php on line 136 and defined 
```

Should I open new issue instead?

**Comment by francoispluchino** [comment]
Ok... There is an issue about it, see #148.

**Comment by bSushil** [comment]
I ran php composer.phar global require "fxp/composer-asset-plugin:~1.0.3" and this solved my problem.

**Comment by SuspiciousPackage** [comment]
Thank you all for your efforts in helping me.

Here's what I did for my windows setup:

Step 1. Deleted all "composer-asset-plugin" folders.

Step 2. Ran   php composer.phar global require "fxp/composer-
asset-plugin:~1.0.3"

Now I can run other commands like diagnose that failed before.  Here's how it looks in the command line.

C:\ProgramData\ComposerSetup\bin>php composer.phar global require "fxp/composer-
asset-plugin:~1.0.3"
Changed current directory to C:/Users/$USERNAME/AppData/Roaming/Composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing fxp/composer-asset-plugin (v1.0.3)
    Downloading: 100%

Writing lock file
Generating autoload files

C:\ProgramData\ComposerSetup\bin>

Now I can run diagnose

C:\wamp\www\laravel\blog>composer diagnose
Checking composer.json: OK
Checking platform settings: FAIL
The xdebug extension is loaded, this can slow down Composer a little.
 Disabling it when using Composer is recommended.
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking composer version: FAIL
You are not running the latest version

   
C:\wamp\www\laravel\blog>composer global update
Changed current directory to C:/Users/$USERNAME/AppData/Roaming/Composer
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing symfony/process (v2.6.4)
  - Installing symfony/process (v2.7.5)
    Downloading: 100%

  - Removing symfony/console (v2.6.4)
  - Installing symfony/console (v2.7.5)
    Downloading: 100%

  - Installing react/promise (v2.2.1)
    Downloading: 100%

  - Removing guzzlehttp/streams (2.1.0)
  - Installing guzzlehttp/streams (3.0.0)
    Downloading: 100%

  - Installing guzzlehttp/ringphp (1.1.0)
    Downloading: 100%

  - Removing guzzlehttp/guzzle (4.2.3)
  - Installing guzzlehttp/guzzle (5.3.0)
    Downloading: 100%

  - Removing laravel/installer (v1.2.0)
  - Installing laravel/installer (v1.2.1)
    Downloading: 100%

Writing lock file
Generating autoload files

C:\wamp\www\laravel\blog>composer -V
Composer version 1.0-dev (790a941cba36842ae74c14c421cbd58200b661ea) 2015-10-01 1
3:48:22

**Comment by francoispluchino** [comment]
It's OK now?

**Comment by SuspiciousPackage** [comment]
Yes so far everything has been great after that. Thank you.

**Pull request merged**
